### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ParagEkbote**
1) I've added 2 new Datasets each under General-purpose, Math & Logic.

2) Also updated the Preference Alignment Section description and included 2 Datasets in it.

### CODE REVIEW

**Comment by mlabonne** [comment]
Hey, thanks for your contribution. Could you remove the pre-training datasets from the general-purpose section? I'm thinking of expanding to pre-training sets later, but this is not the right section for now.

**Comment by ParagEkbote** [comment]
I've removed the pre-training datasets from the general-purpose section. Do let me know if further modifications are required.

**Comment by ParagEkbote** [comment]
I've updated the PR to remove the duplicated dataset.

**Comment by ParagEkbote** [comment]
Can you please review?

cc: @mlabonne

**Comment by ParagEkbote** [comment]
Can you please review?

cc: @mlabonne

**Comment by ParagEkbote** [comment]
Can you please review the PR and suggest any improvements?

cc: @mlabonne

**Comment by ParagEkbote** [comment]
Can you please review the PR and suggest any improvements?

cc: @mlabonne

**Comment by mlabonne** [comment]
Hey sorry about this very long delay, it's all good! Thanks for your contribution, I'll credit you in the next update.

**Comment by ParagEkbote** [comment]
@mlabonne Thank you for merging the PR. I'll continue to contribute if I find valuable datasets that could be added.

**Pull request merged**
